// Spur/Straight Gear


// Set units
@settings(defaultLengthUnit = mm)

// Define a function to create a helical gear
fn straightGear(nTeeth, module, pressureAngle, gearHeight) {
  // Calculate gear parameters
  pitchDiameter = module * nTeeth
  addendum = module
  deddendum = 1.25 * module
  baseDiameter = pitchDiameter * cos(pressureAngle)
  tipDiameter = pitchDiameter + 2 * module

  // Define a function to create a rotated gear sketch on an offset plane
  fn straightGearSketch(offsetHeight) {
    // Calculate the amount to rotate each planar sketch of the gear given the gear helix angle and total gear height
    //helixCalc = acos(offsetHeight * tan(helixAngle) / (tipDiameter / 2))

    // Using the gear parameters, sketch an involute tooth spanning from the base diameter to the tip diameter
    helicalGearSketch = startSketchOn(offsetPlane(XY, offset = offsetHeight))
      |> startProfile(at = polar(angle = 0, length = baseDiameter / 2))
      |> involuteCircular(
           startDiameter = baseDiameter,
           endDiameter = tipDiameter,
           angle = 0,
           tag = $seg01,
         )
      |> line(endAbsolute = polar(angle = 160deg / nTeeth, length = tipDiameter / 2))
      |> involuteCircular(
           startDiameter = baseDiameter,
           endDiameter = tipDiameter,
           angle = -(4 * atan(segEndY(seg01) / segEndX(seg01))),
           reverse = true,
         )

      // Position the end line of the sketch at the start of the next tooth
      |> line(endAbsolute = polar(angle = 360deg / nTeeth, length = baseDiameter / 2))

      // Pattern the sketch about the center by the specified number of teeth, then close the sketch
      |> patternCircular2d(
           instances = nTeeth,
           center = [0, 0],
           arcDegrees = 360deg,
           rotateDuplicates = true,
         )
      |> close()
    return helicalGearSketch
  }

  // Draw a gear sketch on the base plane
  gearSketch001 = straightGearSketch(offsetHeight = 0)

  // Draw a rotated gear sketch on a middle interstitial plane
  gearSketch002 = straightGearSketch(offsetHeight = gearHeight / 2)

  // Draw a rotated gear sketch at the gear height offset plane
  gearSketch003 = straightGearSketch(offsetHeight = gearHeight)

  // Loft each rotated gear sketch together to form a helical gear
  straightGear = loft([
    gearSketch001,
    gearSketch002,
    gearSketch003
  ])

  return straightGear
}

straightGear(
  nTeeth = 30,
  module = 2,
  pressureAngle = 1deg,
  gearHeight = 7,
)
